openapi: 3.0.2
info:
  title: My API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /message:
    get:
      summary: Returns a message
      responses:
        200:
          description: Message returned successfully
          content:
            application/json:
              schema:
                type: string
                example: "Hello, World!"
